#!/bin/sh  

vol=$(($(amixer sget Master | grep 'Left:' | awk -F'[][]' '{ print $2 }' | tr -d '%')))

if (( vol == 0 )); then
	icon="󰝟  "
	color="#f7768e"
elif (( vol < 50 )); then
	icon="󰖀  "
	color="#e0af68"
elif (( vol > 50 && vol < 100 )); then 
	icon="󰕾  "
	color="#9ece6a"
else
	icon="  " 
	color="#73daca"

fi 


if [[ "$1" == "--ICON" ]]; then
	echo $icon 
elif [[ "$1" == "--COLOR" ]]; then
	echo $color 
fi
