format = """
[░▒▓](red)\
[  ](bg:red fg:yellow)\
[](fg:red bg:red)\
$directory\
[](fg:red bg:yellow)\
$git_branch\
$git_status\
[](fg:yellow bg:yellow)\
[](fg:yellow )\
\n$character"""

[directory]
style = "fg:yellow bg:red"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:red"
format = '[[ $symbol $branch ](fg:yellow bg:red)]($style)'

[git_status]
style = "bg:red"
format = '[[($all_status$ahead_behind )](fg:yellow bg:red)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#1d2230"
format = '[[  $time ](fg:#a0a9cb bg:#1d2230)]($style)'
